### ISSUE TITLE
Make the prototype downloadable in the form of respective file extensions by giving a button. 

### ISSUE THREAD

**Issue by s-katte** [s-katte/React-Code-Pen#4]
The user can download the prototype after doing some work, although the code and scripts will be retained unless the browser data is not cleared. It would be great to have this option for convenience.

**Comment by VaibhavSaini19** [comment]
@s-katte I would like to work on this issue

**Comment by s-katte** [comment]
Sure @VaibhavSaini19, assigning it to you.
Happy Hacking!

**Comment by VaibhavSaini19** [comment]
I have a concern though. Since you are using an iframe to render the content, in which the CSS and JS are include within the HTML, I don't think it would be possible to download the content of HTML, CSS, JS separately, as the files aren't linked. I can download the iframe directly though, is it okay?

**Comment by s-katte** [comment]
We could use the help of states may be. Let's try to do, we can go initially with just an HTML file with CSS and JS within it and then try to separate them.
